name: dev
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - libcufile=1.4.0.31
  - pyg=2.3.0
  - ogb=1.3.6
  - networkx=2.8.8
  - wandb=0.15.3
  - jupyter=1.0.0
  - matplotlib=3.6.2
